# Please type or copy the content of Playbook here...
---
- hosts: all
  tasks:
  
    - name: Gather Facts
      cisco.ios.ios_facts:
        gather_subset: all
        
        
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
